// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatusExposed.Database;

#nullable disable

namespace StatusExposed.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220725094133_Add API key field")]
    partial class AddAPIkeyfield
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("StatusExposed.Models.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApiKey");
                });

            modelBuilder.Entity("StatusExposed.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("StatusExposed.Models.ServiceInformation", b =>
                {
                    b.Property<string>("ServicePageDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusPageUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("ServicePageDomain");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("StatusExposed.Models.StatusData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ResponseTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceInformationServicePageDomain")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceInformationServicePageDomain");

                    b.ToTable("StatusData");
                });

            modelBuilder.Entity("StatusExposed.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceInformationServicePageDomain")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceInformationServicePageDomain");

                    b.ToTable("Subscriber");
                });

            modelBuilder.Entity("StatusExposed.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StatusExposed.Models.ApiKey", b =>
                {
                    b.HasOne("StatusExposed.Models.User", "User")
                        .WithMany("ApIKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatusExposed.Models.Permission", b =>
                {
                    b.HasOne("StatusExposed.Models.User", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("StatusExposed.Models.StatusData", b =>
                {
                    b.HasOne("StatusExposed.Models.ServiceInformation", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("ServiceInformationServicePageDomain");
                });

            modelBuilder.Entity("StatusExposed.Models.Subscriber", b =>
                {
                    b.HasOne("StatusExposed.Models.ServiceInformation", null)
                        .WithMany("Subscribers")
                        .HasForeignKey("ServiceInformationServicePageDomain");
                });

            modelBuilder.Entity("StatusExposed.Models.ServiceInformation", b =>
                {
                    b.Navigation("StatusHistory");

                    b.Navigation("Subscribers");
                });

            modelBuilder.Entity("StatusExposed.Models.User", b =>
                {
                    b.Navigation("ApIKeys");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
